# 配置 web 服务器端口
server:
  port: 8080

# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    # druid 连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 60000

# 配置 MyBatisb
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml # MyBatis 的 Mapper 映射文件
  type-aliases-package: com.txw.boot.crud.entity # 映射实体类别名
